# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: 1 Basic Github Actions
# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: [push]
jobs:
  test:
    name: Test
    # https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@master

      # https://github.com/cedrickring/golang-action
      - name: fmt
        uses: cedrickring/golang-action/go1.13@1.5.1
        with:
          args: test -z "`go fmt`"
        env:
          GO111MODULE: "on"

      - name: vet
        uses: cedrickring/golang-action/go1.13@1.5.1
        with:
          args: go vet
        env:
          GO111MODULE: "on"

      - name: test
        uses: cedrickring/golang-action/go1.13@1.5.1
        with:
          args: go test
        env:
          GO111MODULE: "on"
