name: 2 Custom Github Action
on:
  push:
    branches:
      - master

jobs:
  inline_action:
    name: Inline Action
    runs-on: ubuntu-latest
    steps:
      - name: inline action
        run: |
          echo "Hello World"
          echo "How are you going?"

  in_repo_action:
    name: In-Repo Action
    runs-on: ubuntu-latest
    steps:
      # Note: this is required, so that the next action has been checked out and is available
      - name: clone
        uses: actions/checkout@master

      - name: in-repo action
        uses: ./.github/actions/greeting
        with:
          args: Wyzant Tech Talks

  third_party_actions:
    name: Third Party Actions
    runs-on: ubuntu-latest
    steps:
      - name: Third-party JS action
        uses: actions/hello-world-javascript-action@master
        with:
          who-to-greet: "Wyzant tech talks"

