name: 3 Issue Creation Trigger
on:
  issues:
    types: [opened]

jobs:
  label:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: clone
        uses: actions/checkout@master

      - name: javascript action
        uses: ./.github/actions/js-labeler
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
