name: Test
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@master

      # https://github.com/cedrickring/golang-action
      - name: fmt
        uses: cedrickring/golang-action/go1.13@1.5.1
        with:
          args: test -z "`go fmt`"
        env:
          GO111MODULE: "on"

      - name: vet
        uses: cedrickring/golang-action/go1.13@1.5.1
        with:
          args: go vet
        env:
          GO111MODULE: "on"

      - name: test
        uses: cedrickring/golang-action/go1.13@1.5.1
        with:
          args: go test
        env:
          GO111MODULE: "on"
